### PR TITLE
scp to/from device working

### PR DESCRIPTION
**Pull request by semaphore**
modified and built scp and dbclient from https://github.com/mkj/dropbear (pr-66)
ldid2 both with the default.ent
replaced them in the iosbinpack.tar
small modifications to the ViewController.m

### CODE REVIEW

**Comment by jakeajames** [comment]
Since I don't want people to uninstall, I'll get the binaries and make a separate tar for them, which binaries did you update, just scp and dbclient?

**Comment by semaphore** [comment]
dropbear - either recompile with the path fixed (default is "/usr/bin:/bin") or patch it out to something like "/var/bin;/bin")

scp - easier to recompile with:
#define DROPBEAR_PATH_SSH_PROGRAM "/var/containers/Bundle/iosbinpack64/usr/local/bin/dbclient"
but can also probably be patched out for the lazy.

dbclient - this may be able to be patched but I found it simpler to just update the default_options.h in dropbear and build both scp and dbclient.

also, note that since dropbear is setting the PATH to (whatever you change it to) make sure that scp is in /var/bin (or in said PATH) otherwise scp OTHER -> DEVICE will not work and give an unknown command because scp won't be in the PATH on the device. scp DEVICE -> OTHER works fine also.

**Comment by filippocld** [comment]
Is it possible to also make sftp-server work somehow? I hate having to do 300 steps to just transfer files from a device to another

**Comment by semaphore** [comment]
It is ;) I have one working but there's a bug that I'm currently fixing.

**Comment by filippocld** [comment]
Great!
I tried doing it myself by just installing OpenSSL and the sftp + sftp-server packages from the respective deb files but it didn’t work: the binary runs but a client still can’t connect

**Comment by nunsie** [comment]
fails to add the generated public key to authorized_keys rendering the private key outputted useless, maybe an option in the UI for priv/pub key gen vs password?

**Pull request closed without merging**
