### PR TITLE
Increased success rates of voucher_swap

### PR DESCRIPTION
**Pull request by peterprd**
I opened an issue before about success rates, and these changes made success rates to almost 96%

### CODE REVIEW

**Comment by clarityzzz** [comment]
#38

**Comment by StrugglingDoge** [comment]
Thanks for making a PR. Hopefully gets merged since this fixes Pro devices being unable to run rootless. Also just improves success rate overall.

**Comment by peterprd** [comment]
@clarityzzz Not based on that, But It seems the same.

**Comment by peterprd** [comment]
@StrugglingDoge I am not the only on who couldn’t run rootlessJB without this or my trick to increase success rates!

**Pull request merged**
